name: Generate Snake Contribution Grid

on:
  schedule:
    - cron: "0 0 * * *" # Runs once a day at midnight
  workflow_dispatch: # Allows manual execution

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Generate Contribution Snake
        uses: Platane/snk@v3
        with:
          github_user_name: bavindushan
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Upload Snake SVG
        uses: actions/upload-artifact@v3
        with:
          name: snake-artifact
          path: dist

      - name: Commit and Push Snake SVG
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add dist/github-contribution-grid-snake.svg
          git commit -m "Updated contribution snake animation" || echo "No changes to commit"
          git push
